apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "my-python-job.fullname" . }}
  labels:
    {{- include "my-python-job.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "my-python-job.labels" . | nindent 8 }}
    spec:
      containers:
        - name: helloworld
          image: python:3
          command: ["python", "-c"]
          args: [{{ .Values.truc }}]
      restartPolicy: Never
